# Generated by Django 5.1.1 on 2024-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genreTwo',
            field=models.CharField(default=900, max_length=100),
            preserve_default=False,
        ),
    ]
