# Generated by Django 5.1.1 on 2024-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_genretwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genreOne',
            field=models.CharField(default=900, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='genreThree',
            field=models.CharField(default=900, max_length=100),
            preserve_default=False,
        ),
    ]
