# Generated by Django 5.1.1 on 2024-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_genreone_movies_genrethree'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
