# Generated by Django 5.1.1 on 2024-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.CharField(default=999, max_length=10),
            preserve_default=False,
        ),
    ]
